-- Create the orders table
create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  order_id text not null,
  name text not null,
  phone text not null,
  area text not null,
  address text not null,
  items jsonb not null,
  subtotal numeric not null,
  delivery_fee numeric not null,
  total numeric not null,
  status text not null default 'pending'::text,
  payment_method text not null
);

-- Enable Row Level Security (RLS)
alter table public.orders enable row level security;

-- Create policies

-- 1. Allow public (unauthenticated) users to INSERT orders
create policy "Enable insert for everyone" 
on public.orders 
for insert 
with check (true);

-- 2. Allow authenticated users (admins) to SELECT (view) all orders
create policy "Enable select for authenticated users only" 
on public.orders 
for select 
using (auth.role() = 'authenticated');

-- 3. Allow authenticated users (admins) to UPDATE orders (e.g., change status)
create policy "Enable update for authenticated users only" 
on public.orders 
for update 
using (auth.role() = 'authenticated');
